version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: shop-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - images:/etc/nginx/images
    depends_on:
      - server
      - ui
    networks:
      - app-connect

  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - ../../server/.env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-connect

  server:
    container_name: shop-backend
    image: ${DOCKER_USERNAME}/shop-backend:${IMAGE_TAG}
    restart: always
    ports:
      - "4000:4000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../server/.env.dev
    volumes:
      - images:/usr/src/app/server-uploads
    networks:
      - app-connect

  ui:
    container_name: shop-client
    image: ${DOCKER_USERNAME}/shop-client:${IMAGE_TAG}
    restart: always
    ports:
      - "3000"
    env_file:
      - ../../client/.env.dev
    depends_on:
      - server
    networks:
      - app-connect

  stripe:
    container_name: shop-stripe-cli
    image: stripe/stripe-cli:v1.21.5
    restart: always
    command: listen --forward-to http://server:4000/api/webhook/stripe --skip-verify
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_DEVICE_NAME: docker-stripe-cli
    depends_on:
      - server
    networks:
      - app-connect

volumes:
  db_data:
  images:

networks:
  app-connect:
    driver: bridge
