version: "3.3"

services:
  nginx:
    image: nginx:alpine
    container_name: shop-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - images:/etc/nginx/images

    depends_on:
      - server
      - ui
    networks:
      - app-connect
  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - ../../server/.env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-connect

  # prisma-studio:
  #   container_name: prisma-studio
  #   image: node:18-alpine
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - "5556:5555"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/mystore-dev
  #     - NODE_ENV=development
  #   depends_on:
  #     - db
  #   command: npx prisma studio --host 0.0.0.0 --port 5555
  #   networks:
  #     - app-connect

  server:
    container_name: shop-backend
    restart: always
    build:
      context: ../../server
      dockerfile: Dockerfile.dev
    # uncomment network_mode variable to be able to run docker in localhost +
    # network_mode: host
    ports:
      - "4000:4000"
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../server/.env.dev
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 15s
    volumes:
      - ../../server:/usr/src/app
      - /usr/src/app/node_modules
      # - uploads:/usr/src/app/server-uploads
      # - ../../server/server-uploads:/usr/src/app/server-uploads
      - images:/usr/src/app/server-uploads
    networks:
      - app-connect
  ui:
    container_name: shop-client
    build:
      context: ../../client
      dockerfile: Dockerfile.dev
    # uncomment network_mode variable to be able to run docker in localhost -
    # network_mode: host
    ports:
      - "3000"
      # - "443:443"
      # generate certs and move it in /etc/nginx/certs directory
      # sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout private.key -out certificate.crt
    # volumes:
    #  - /etc/nginx/certs:/etc/nginx/certs

    env_file:
      - ../../client/.env.dev

    # environment:
    #   NODE_ENV: production
    #   APP_URL: ${APP_URL}
    #   APP_DOMAIN: ${APP_DOMAIN}
    #   SERVER_URL: ${SERVER_URL}
    #   NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    networks:
      - app-connect
    depends_on:
      - server
    # depends_on:
    #   server:
    #     condition: service_healthy
    # volumes:
    #   - uploads:/usr/src/app/server-uploads

volumes:
  db_data:
  images:

networks:
  app-connect:
    driver: bridge
