export enum EnumSubscriptionStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  PENDING_DOWNGRADE = 'PENDING_DOWNGRADE',
  UPGRADING = 'UPGRADING',
  OVERDUE = 'OVERDUE',
  PAUSED = 'PAUSED',
  TRIALING = 'TRIALING',
}
