export const EnvVariables = {
  DATABASE_URL: 'DATABASE_URL',
  CLIENT_URL: 'CLIENT_URL',
  SERVER_URL: 'SERVER_URL',
  SERVER_DOMAIN: 'SERVER_DOMAIN',

  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',

  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',

  YOOKASSA_SHOP_ID: 'YOOKASSA_SHOP_ID',
  YOOKASSA_SECRET_KEY: 'YOOKASSA_SECRET',

  STRIPE_PUBLIC_KEY: 'STRIPE_PUBLIC_KEY',
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',
};
