export const EnvVariables = {
  CLIENT_URL: 'CLIENT_URL',
  SERVER_URL: 'SERVER_URL',
  SERVER_DOMAIN: 'SERVER_DOMAIN',

  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',

  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',

  YOOKASSA_SHOP_ID: 'YOOKASSA_SHOP_ID',
  YOOKASSA_SECRET_KEY: 'YOOKASSA_SECRET',

  STRIPE_PUBLIC_KEY: 'STRIPE_PUBLIC_KEY',
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',

  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_HOST: 'locDB_HOST',
  DB_PORT: 'DB_PORT',
  DB_DATABASE: 'DB_DATABASE',
  DB_URI: 'DB_URI',

  MAIL_HOST: 'MAIL_HOST',
  MAIL_PORT: 'MAIL_PORT',
  MAIL_USER: 'MAIL_USER',
  MAIL_PASSWORD: 'MAIL_PASSWORD',
};
