export const QUERY_KEYS = {
  auth: ['auth user'],
  profile: ['profile'],
  createStore: ['create-store'],
  updateStore: ['update-store'],
  deleteStore: ['delete-store'],
  mainStatistics: ['main-statistics'],
  middleStatistics: ['middle-statistics'],
  store: ['store'],
  createProduct: ['create-product'],
  updateProduct: ['update-product'],
  deleteProduct: ['delete-product'],
  getStoreProducts: ['get-store-products'],
  getProductById: ['get-product-by-id'],
  createColor: ['create-color'],
  updateColor: ['update-color'],
  deleteColor: ['delete-color'],
  getStoreColors: ['get-store-colors'],
  getColorById: ['get-color-by-id'],
  createCategory: ['create-category'],
  updateCategory: ['update-category'],
  deleteCategory: ['delete-category'],
  getStoreCategories: ['get-store-categories'],
  getCategoryById: ['get-category-by-id'],
  createBrand: ['create-brand'],
  updateBrand: ['update-brand'],
  deleteBrand: ['delete-brand'],
  getStoreBrands: ['get-store-brands'],
  getBrandById: ['get-brand-by-id'],
  uploadImage: ['upload-image'],
  getStoreReviews: ['get-store-reviews'],
  productExplorer: ['product-explorer'],
  logout: ['logout'],
  productId: (id: string) => ['product', id],
  product: ['product'],
  toggleFavorite: ['toggle-favorite'],
  deleteReview: ['delete-review'],
  createReview: ['create-review'],
  checkout: ['checkout'],
};