version: "3.3"

services:
  nginx:
    image: nginx:alpine
    container_name: shop-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/usr/src/app/server-uploads:ro

    depends_on:
      - server
      - ui
    networks:
      - app-connect
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    # ports:
    #   - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-connect

  prisma-studio:
    container_name: prisma-studio
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mystore-dev
      - NODE_ENV=development
    depends_on:
      - db
    command: npx prisma studio
    networks:
      - app-connect

  server:
    container_name: shop-backend
    restart: always
    build:
      context: ../../server
      dockerfile: Dockerfile.prod
    # uncomment network_mode variable to be able to run docker in localhost +
    # network_mode: host
    ports:
      - "4000"
      - "5555"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../../server/.env.prod
    #volumes:
    #  - /opt/<projectName>/logs/server:/usr/src/app/log
    environment:
      CLIENT_URL: ${CLIENT_URL}
      SERVER_URL: ${SERVER_URL}
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_URI: ${DB_URI}
      NODE_ENV: development

    # command: sh -c "npx prisma migrate deploy && npm run start:dev"

    volumes:
      - uploads:/usr/src/app/server-uploads
    networks:
      - app-connect
  ui:
    container_name: shop-client
    build:
      context: ../../client
      dockerfile: Dockerfile.prod
    # uncomment network_mode variable to be able to run docker in localhost -
    # network_mode: host
    ports:
      - "3000"
      # - "443:443"
      # generate certs and move it in /etc/nginx/certs directory
      # sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout private.key -out certificate.crt
    # volumes:
    #  - /etc/nginx/certs:/etc/nginx/certs

    env_file:
      - ../../client/.env.prod

    environment:
      NODE_ENV: production
      APP_URL: ${APP_URL}
      APP_DOMAIN: ${APP_DOMAIN}
      SERVER_URL: ${SERVER_URL}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    networks:
      - app-connect
    depends_on:
      - server
    # volumes:
    #   - uploads:/usr/src/app/server-uploads
    links:
      - server

volumes:
  db_data:
  uploads:

networks:
  app-connect:
    driver: bridge
