events {
    worker_connections 1024;
}

http {

    upstream app_server {
        server server:4000;
        keepalive   100;
    }
    upstream client {
        server ui:3000;
    }


    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Uploads - прямо к backend
        location /server-uploads/ {
            # alias /usr/src/app/server-uploads/;
            # expires 30d;
            # add_header Cache-Control "public, immutable";

            proxy_pass http://server/server-uploads/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        # API
        location /api/ {
            proxy_pass http://app_server;
            # proxy_http_version 1.1;
            # proxy_set_header Upgrade $http_upgrade;
            # proxy_set_header Connection 'upgrade';
            # proxy_set_header Host $host;
            # proxy_cache_bypass $http_upgrade;
        }

        # Frontend
        location / {
            proxy_pass http://client;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
        # location / {
        #     root        /usr/share/nginx/html;
        #     index  index.html index.htm;
        #     try_files   $uri /index.html;
        # }

        # error_page   500 502 503 504  /50x.html;
        # location = /50x.html {
        #     root   /usr/share/nginx/html;
        # }
    }
}