name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI - Build and Push Release Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via script
        run: |
          cd /home/ubuntu/shop-next-nest/docker/dev

          ./start-pull.sh
