# This workflow is triggered after the successful completion of the CI pipeline.
# First need to create a github action runner on your server and set it to run jobs with label 'self-hosted'.
# Link to create runner - https://github.com/albertaghajanyanswe/shop-next-nest/settings/actions/runners/new?arch=x64&os=linux

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI - Build and Push Release Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy via script
        run: |
          cd /home/ubuntu/shop-next-nest/docker/dev

          ./start-pull.sh
